[package]
name = "soter-v2"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
glob = "0.3.2"
log = "0.4.27"
log4rs = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
